### ISSUE TITLE
Updating user agent 

### ISSUE THREAD

**Issue by chiragw15** [loklak/loklak_jlib_api#3]
This is in reference to this issue. https://github.com/fossasia/loklak_wok_android/issues/16 . This is the current user agent we are using.
`Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.4; en-US; rv:1.9.2.2) Gecko/20100316 Firefox/3.6.2`

And according to twitter.
```
If you log in to twitter.com on the following browsers, you will be directed to see mobile.twitter.com.
Internet Explorer, version 10 or earlier
Safari, version 6 or earlier
Chrome, version 9 or earlier
Firefox, version 9 or earlier
```
The code in TwitterScrapper.java file is written according to twitter.com and not mobile.twitter.com. Thus the app is crashing. 

@sudheesh001 Does this seem valid to you?

**Comment by sudheesh001** [comment]
Looks valid. @Orbiter Can you have a look please.
