### ISSUE TITLE
Unable to Scrape Images, Videos and GIFs (and their thumbnails)

### ISSUE THREAD

**Issue by SKrPl** [loklak/loklak_jlib_api#5]
In TwitterScrapper class (search method):
1. Images are scraped using **class=\"media media-thumbnail twitter-timeline-link media-forward is-preview"**, as the relevant tags for images are changed to,  **class=\"AdaptiveMedia-photoContainer"** with key **data-image-url**, the scraper can't extract images from html text.
2. The same goes for videos and GIFs, the provided tags and keys in source code doesn't work. Required video details are in **<video class=\"visible** with key **src** (the link of video is prefixed with *_glob:* , trying to open that link in a new tab in browser doesn't redirect to the video, it says twitter can't find it). GIFs have also the same **<video class=\"visible** and key **src** (link is _not_ prefixed with _glob:_ , and we can open the link in a new tab, it shows the GIF).
3. The thumbnail of videos and GIFs can be obtained using **div class=\"poster-image** and key is **style** (the _value_ of key needs to be processed to obtain the url, example of *value*  is ... **background-image: url("https://pbs.twimg.com/tweet_video_thumb/C7VwFXsU4AAmpE9.jpg"); display: none;**  ).

Now the problem with videos and GIFs is that they are being loaded by Javascript, so we don't get the required details in *GET* request made by HttpsUrlConnection's object (we only get the things provided by html, in this case, details of images).

@Orbiter What do you suggest ?

**Comment by sudheesh001** [comment]
@Orbiter Looks valid. What's your opinion on this ?

**Comment by sudheesh001** [comment]
Looks closely related to https://github.com/loklak/loklakj_lib/issues/3

**Comment by SKrPl** [comment]
Closing this as loklak-jlib-api no longer provides scraping of twitter. The scraping features are implemented in https://github.com/fossasia/loklak_scraper_js .
